site_name: Notas musicais
repo_url: https://github.com/vladimirmaciel/nostas-musicais/
repo_name: vladimirmaciel/notas-musicais
edit_uri: tree/main/docs/
favicon: assets/favicon.png

theme:
    name: material
    language: pt-BR
    logo: assets/logo.png
markdown_extensions:
    - attr_list
extra_css:
  - stylesheets/extra.css
